#All units in meters
standalone_tags:
  [
    {id: 0, size: 0.1825}
    # {id: 0, size: 0.158}
  ]

tag_bundles:
  [
    # {
    #   name: 'marker_bundle',
    #   layout:
    #     [
    #       {id: 0, size: 0.0800, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
    #       {id: 1, size: 0.0700, x: -0.0777, y: -0.0036, z: 0.0242, qw: 0.9536, qx: 0.0029, qy: 0.3008, qz: 0.0107},
    #       {id: 2, size: 0.0700, x: 0.0771, y: -0.0059, z: 0.0248, qw: 0.9682, qx: 0.0185, qy: -0.2496, qz: -0.0055}
    #     ]
    # }
  ]
 